name: build
on:
  pull_request:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/master' }}

      - name: Run build command
        run: cargo build --release --frozen

      - name: Update README build info
        shell: bash
        run: python scripts/update_readme.py

      - name: Commit README on main
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        shell: bash
        run: bash ./scripts/commit_readme_if_changed.sh
